# Netlify Configuration File
# This file configures the Netlify deployment for the Jam3a project

# Build settings
[build]
  # Directory to publish (the static site output)
  publish = "dist"
  
  # Default build command
  command = "npm run build"

# Redirects and rewrites
[[redirects]]
  # Redirect all paths to index.html for client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to set on files
[[headers]]
  # Define headers for all files
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https:;"

# Environment variables
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
