name: jam3a-app
services:
- name: frontend
  github:
    repo: Samerabualsoud/Jam3a-2.0
    branch: main
    deploy_on_push: true
  build_command: npm install && npm run build
  run_command: npx serve -s dist
  http_port: 3001
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_API_URL
    value: ${app.BACKEND_URL}

- name: backend
  github:
    repo: Samerabualsoud/Jam3a-2.0
    branch: main
    deploy_on_push: true
  build_command: cd server && npm install
  run_command: cd server && node server.js
  http_port: 5000
  routes:
  - path: /api
  envs:
  - key: NODE_ENV
    value: production
  - key: MONGO_URI
    value: ${db.DATABASE_URL}
  - key: JWT_SECRET
    value: ${_self.JWT_SECRET}
  - key: PORT
    value: "5000"
  - key: RATE_LIMIT_WINDOW_MS
    value: "900000"  # 15 minutes in milliseconds
  - key: RATE_LIMIT_MAX_REQUESTS
    value: "100"     # Maximum requests per window
  - key: LOG_LEVEL
    value: "info"    # Log level for production
  - key: LOG_RETENTION_DAYS
    value: "14"      # Log retention period in days
  - key: CORS_ORIGIN
    value: "${_self.APP_URL}" # Frontend URL for CORS

databases:
- name: mongodb
  engine: mongodb
  version: "5"
  cluster_size: db-s-1vcpu-1gb
  production: true
  db_name: jam3a_db
  db_user: jam3a_admin

envs:
- key: JWT_SECRET
  value: "jam3a_jwt_secret_production"
  type: SECRET
- key: APP_URL
  value: "https://jam3a-app.ondigitalocean.app"
  type: GENERAL
